- name: Play Variables
  hosts: localhost
  vars:
    URL: play example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play Variables from files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Task Variables from files
  hosts: localhost
  tasks:
    - name: print play variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}
  

- name: Vars from Inventory
  hosts: all
  tasks:
    - name: print play variable Inventory
      ansible.builtin.debug:
        msg: URL = {{ URL }}




       